# site settings
title: Jeremy Patterson
subtitle: Physical Hydrogeology
email: jp128@rice.edu
description: "Not all who wander are lost."
url: "https://jrpatterson79.github.io" # the base hostname & protocol for your site
author:
street_address_1: Rice University
street_address_2: Earth, Environmental, and Planetary Sciences
city: Houston
state: TX
zip_code: 77027
country: 
phone: 

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jrpatterson79
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/jpatterson3/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/FractureRockH20

permalink: /:title/

# build settings
markdown: kramdown

sass:
  style: compressed
